---
title: "My Sample R Codes"
output: html_document
date: "2022-10-01"
---

# LOAD DATA 

```{r}
library(datasets)
```

# SUMMARIZE DATA

```{r}
head(iris)
summary(iris)
plot(iris)
```

# CLEAN UP
# Clear packages
```{r}
detach("package:datasets", unload = TRUE)
```
# Clear plots
```{r}
dev.off()
```
# Clear console
Ctrl+L

# LOAD PACKAGES
# Install packages
```{r}
install.packages("pacman")
library(pacman)
```
# These are the packages I load every time.
```{r}
pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, ggvis, httr, lubridate, plotly, rio, rmarkdown, shiny, stringr, tidyr)
```

# LOAD BASE PACKAGES
```{r}
library(datasets)
```

# LETS LOOK AT THE iris DATASET
```{r}
head(iris)
```

# CREATE PLOTS
# Categorical variable
```{r}
plot(iris$Species)
```
# Quantitative variable
```{r}
plot(iris$Petal.Length)
```
# Cat + Quant
```{r}
plot(iris$Species, iris$Petal.Width)
```
# Quant pair
```{r}
plot(iris$Petal.Length, iris$Petal.Width)
```
# Enttire data frame
```{r}
plot(iris)
```
